### ISSUE TITLE
An event's "start" date property should accept times other that 00:00:00:000

### ISSUE THREAD

**Issue by andrewbeng89** [Trekels/vue2-calendar#25]
#### Issue description

Any event which has a `start` date not set to `00:00:00:000` will not be displayed as expected in the `<events-box>` component.

#### Steps to reproduce the issue

1.  Vue.js state and template setup
```
// script
events: [
  {
    classes: ['c-4caf50'],
    id: 'dpaevt:99-e-4172384'
    start: new Date('Wed May 09 2018 10:30:00 GMT+0200 (CEST)')
    title: 'Pressefrühstück zum Projekt zur Müllreduzierung mit Bezirksbürgermeister von Neukölln, Martin Hikel''
  }
]
...

// template
<vue-calendar :events="events">
```

#### What's the expected result?

- Single event should be displayed in the month of May (09.05.2018).

#### What's the actual result?

- No events are displayed in May.

#### Additional details / screenshot

* Expected event not displayed:
<img width="1388" alt="vue2-simple-calendar_event-not-displayed" src="https://user-images.githubusercontent.com/2418932/41160547-5d3d3082-6b30-11e8-82ec-765670c040fd.png">

* The event is displayed if the time is set to `00:00:00:000`:
<img width="1380" alt="screen shot 2018-06-08 at 15 30 07" src="https://user-images.githubusercontent.com/2418932/41160741-e608cb10-6b30-11e8-8cb8-bcb5babe8a8e.png">

**Comment by Trekels** [comment]
@andrewbeng89 I made a change to the way event dates are checked, can you check if v1.0.8 resolves your issue ?

**Comment by andrewbeng89** [comment]
Hi @Trekels, sorry for the late reply. The changes in the latest version fixes this issue. Thanks for the fix!
