### ISSUE TITLE
v-html directive

### ISSUE THREAD

**Issue by shoomakov** [Trekels/vue2-calendar#3]
Hi, are you accept pull request with some changes, like:
` <div class="event" v-html="event.title"></div> `

Custom event titles needed

https://github.com/Trekels/vue2-calendar/blob/31ba4f33d93d1db90da0529fb8c76bc86131d1c8/src/components/events-box.vue#L8

**Comment by Trekels** [comment]
@shoomakov I think v-html is not the best solution here, would a slot be suitable for you ?

**Comment by shoomakov** [comment]
@Trekels slot is even better
